### ISSUE TITLE
Compuertas logicas 

### ISSUE THREAD

**Issue by Ivan-PerezZ** [SistemasTecTlaxiaco/compuertas-logicas-equipo-maetzy-quetzaly-angel-jesus#1]
[Practica y simulador con practica real.pdf](https://github.com/user-attachments/files/18068975/Practica.y.simulador.con.practica.real.pdf)

**Comment by Eddi3mendoz** [comment]
Portada:25/25
Procedimiento/Desarrollo:24/25
Figuras, Ilustraciones y Fotografías:23/25
Resultados y conclusiones:25/25
Total:19.4

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
